prog: td.o raster.o renderer.o model.o animator.o clear_qk.o 
	cc68x -g td.o clear_qk.o raster.o renderer.o model.o animator.o -o prog
	
test: td.o raster.o renderer.o model.o animator.o clear_qk.o 
	cc68x -g td.o clear_qk.o raster.o renderer.o model.o animator.o -o test

td.o: td.c raster.o renderer.o model.o animator.o
	 cc68x -g -c td.c	

clear_qk.o: clear_qk.s
		gen -D -L2 clear_qk.s
 
animator.o: animator.c animator.h model.h raster.h td.h
	cc68x -g -c animator.c
 
raster.o: raster.c raster.h
	cc68x -g -c raster.c		

model.o: model.c model.h
	cc68x -g -c model.c

renderer.o: renderer.c renderer.h model.h raster.h
	cc68x -g -c renderer.c


